game_env:
  name: "twenty_forty_eight"
  description: "2048 game environment"
  env_type: "custom"
  render_mode: "human"
  max_steps: 1000
  seed: 42
  num_runs: 3

agent:
  # Global agent settings
  name: "2048_agent"
  model_name: "claude-3-7-sonnet-latest"
  cache_dir: "cache/twenty_forty_eight"
  reasoning_effort: "high"
  token_limit: 100000
  harness: true # Whether to use the perception-memory-reasoning pipeline
  observation_mode: "text"
  # Module-specific settings
  modules:
    base_module:
    
    perception_module:

    memory_module:
      max_memory: 10  # Maximum number of memory entries to store
      use_reflection: False  # Whether to reflect on past memories, default is True
    
    reasoning_module:
