game_env:
  name: "ace_attorney"
  description: "Ace Attorney game environment using retro.Env and GymEnvAdapter."
  env_type: "retro"
  max_steps: 3000
  seed: null
  num_runs: 1

agent:
  name: "ace_attorney_retro_agent"
  model_name: "gemini-2.5-pro-preview-03-25"
  cache_dir: "cache/retro_ace_attorney" 
  harness: true
  observation_mode: "both" # "vision", "text", or "both"
  
  modules:
    base_module:
    
    perception_module: 

    memory_module:
      max_memory: 5
    
    reasoning_module:
      use_perception: True
      use_memory: True
      use_cot: True 