game_env:
  name: "doom"
  description: "Doom game environment"
  env_type: "custom"
  render_mode: "human"
  max_steps: 300
  seed: 42
  num_runs: 1
  doom_scenario_path: "basic.wad"
  doom_map: "map01"
  living_reward: 1
  screen_resolution: "RES_320X240"
  screen_format: "CRCGCB"
  render_hud: true
  render_crosshair: false
  render_weapon: true
  render_decals: false
  render_particles: false
  window_visible: true
  episode_start_time: 14
  available_buttons:
    - MOVE_UP
    - MOVE_DOWN
    - MOVE_LEFT
    - MOVE_RIGHT
    - ATTACK
  available_game_variables:
    - AMMO2
  mode: "PLAYER"
  doom_skill: 5
  rewards:
    kill_monster: 106
    shot_penalty: -5

agent:
  name: "doom_agent"
  model_name: "gpt-4o"
  cache_dir: "cache/doom"
  reasoning_effort: "high"
  token_limit: 100000
  harness: false
  observation_mode: "vision"

  modules:
    base_module:
      observation_mode: "vision"

    perception_module:
      observation_mode: "vision"

    memory_module:
      max_memory: 15

    reasoning_module:
      use_perception: true
      use_memory: true
      use_cot: true