game_env:
  name: "doom"
  description: "Doom game environment"
  env_type: "retro"
  render_mode: "human"
  max_steps: 500
  seed: 42
  num_runs: 1

agent:
  # Global agent settings
  name: "doom_agent"
  model_name: "claude-3-7-sonnet-latest"
  cache_dir: "cache/doom"
  reasoning_effort: "high"
  token_limit: 100000
  harness: false
  observation_mode: "vision"
  # Module-specific settings
  modules:
    base_module:
    
    perception_module:

    memory_module:
      max_memory: 15  # Maximum number of memory entries to store
    
    reasoning_module:
      use_perception: True
      use_memory: True
      use_cot: True